# Generated by Django 6.0.2 on 2026-02-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_group', models.CharField(blank=True, max_length=100, null=True)),
                ('item_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_group', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_master',
            },
        ),
    ]
