# Generated by Django 6.0.2 on 2026-03-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('site_name', models.TextField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GRNHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transport', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('receive_location', models.TextField(blank=True, db_column='receive_location', null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('gate_pass_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grn_header',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_group', models.CharField(blank=True, max_length=50, null=True)),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_group', models.CharField(blank=True, max_length=100, null=True)),
                ('item_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_group', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_master',
                'ordering': ['item_name', 'item_code'],
                'unique_together': {('item_name', 'grade_group')},
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('unique_item_id', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('thickness', models.FloatField(default=0)),
                ('challan_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authapi.grnheader')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapi.materialmaster')),
            ],
            options={
                'db_table': 'grn_item',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('unique_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('thickness', models.FloatField(default=0)),
                ('challan_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='authapi.grnheader')),
                ('grn_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapi.grnitem')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
