# Generated by Django 6.0.2 on 2026-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('site_name', models.TextField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
    ]
