# Generated by Django 6.0.2 on 2026-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
