# Generated by Django 6.0.2 on 2026-03-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_projectmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='BALABHARTI INFRASTRUCTURE PVT LTD', max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('receive_location', models.CharField(max_length=255)),
                ('grn_no', models.CharField(max_length=100)),
                ('grn_date', models.DateTimeField()),
                ('gate_pass_no', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectmaster',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('challan_qty', models.FloatField()),
                ('total_qty', models.FloatField()),
                ('balance_qty', models.FloatField()),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authapi.grnheader')),
            ],
        ),
    ]
