# Generated by Django 6.0.2 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_grnheader_alter_projectmaster_options_grnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnheader',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='balance_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='challan_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='grnheader',
            table='grn_header',
        ),
        migrations.AlterModelTable(
            name='grnitem',
            table='grn_item',
        ),
        migrations.AlterModelTable(
            name='projectmaster',
            table='project_master',
        ),
    ]
