# Generated by Django 6.0.2 on 2026-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0004_alter_grnheader_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnheader',
            name='grn_date',
            field=models.DateField(),
        ),
    ]
