# Generated by Django 6.0.2 on 2026-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0005_alter_grnheader_grn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnheader',
            name='receive_location',
        ),
        migrations.RemoveField(
            model_name='grnheader',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='grnheader',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grnheader',
            name='received_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grnheader',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='gate_pass_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='grn_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='grn_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grnheader',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
