# Generated by Django 6.0.2 on 2026-03-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0006_remove_grnheader_receive_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnheader',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='materialmaster',
            options={'ordering': ['item_name', 'item_code']},
        ),

        migrations.AddField(
            model_name='grnitem',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapi.materialmaster'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='thickness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='unique_item_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='grade_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='balance_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='materialmaster',
            unique_together={('item_name', 'grade_group')},
        ),
    ]
