# Generated by Django 6.0.2 on 2026-03-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('authapi', '0007_alter_grnheader_options_alter_materialmaster_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('unique_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='authapi.grnheader')),
                ('grn_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapi.grnitem')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
