# Generated by Django 6.0.2 on 2026-03-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0009_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnheader',
            old_name='received_location',
            new_name='receive_location',
        ),
    ]
